# Permalinks
permalink:           /:title.html

# Setup
title:               RWeekly.org - Weekly Updates from the R Community
url:                 https://rweekly.org
paginate:            1
baseurl:             ""
nav-baseurl:         "https://rweekly.org"
ampdir: amp
description: Get the latest updates and blog posts about the statistical programming R language.
post_max: 396+24

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              R Weekly
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rweekly/rweekly.org

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag

pages_list:       
  About: '/about.html'
  Random: '/random.html'
  Archive: '/archive.html'
  Feed: '/atom.xml'
  Draft: '/draft.html'